-- ====================================================================
-- MASTER SQL SCHEMA FOR MASJID CITRA SENTUL RAYA (SUPABASE DATABASE)
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard)
-- ====================================================================

-- 1. EXTENSIONS & SETUP
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------------------
-- 2. TABLE: programs (ZISWAF & Wakaf Programs)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.programs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kategori VARCHAR(50) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    terkumpul_persen INT DEFAULT 0,
    terkumpul_rp NUMERIC(15, 2) DEFAULT 0,
    target_rp NUMERIC(15, 2) DEFAULT 0,
    donatur INT DEFAULT 0,
    gambar TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial programs
INSERT INTO public.programs (id, kategori, judul, deskripsi, terkumpul_persen, terkumpul_rp, target_rp, donatur, gambar)
VALUES 
(1, 'infaq', 'Pembangunan Masjid Citra Sentul Raya', 'Wakaf pembangunan masjid. Amal Jariyah Tak Terputus.', 0, 0, 1500000000, 0, 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=800&q=80'),
(2, 'sedekah', 'Santunan Yatim Piatu', 'Berbagi Kasih Bersama Anak Yatim.', 0, 0, 250000000, 0, 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80'),
(3, 'zakat', 'Santunan Dhuafa (& Fakir Miskin)', 'Meringankan Beban Saudara Kita.', 0, 0, 750000000, 0, 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------------------
-- 3. TABLE: donations (Riwayat Transaksi & Donasi Jamaah)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.donations (
    id VARCHAR(100) PRIMARY KEY,
    tanggal VARCHAR(50) NOT NULL,
    program_id BIGINT REFERENCES public.programs(id) ON DELETE SET NULL,
    program_name VARCHAR(255) NOT NULL,
    nominal NUMERIC(15, 2) NOT NULL,
    metode VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'Menunggu Verifikasi',
    bukti TEXT,
    nama_donatur VARCHAR(255) DEFAULT 'Hamba Allah',
    kontak_donatur VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial donation
INSERT INTO public.donations (id, tanggal, program_id, program_name, nominal, metode, status, bukti, nama_donatur, kontak_donatur)
VALUES 
('INV-9823', '23 Agt 2026', 2, 'Santunan Yatim Piatu', 150000, 'Bank Transfer (BSI)', 'Berhasil', NULL, 'Hamba Allah', '0812xxxx')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------------------
-- 4. TABLE: registered_jamaah (Data Akun Jamaah Terdaftar)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.registered_jamaah (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nama VARCHAR(255) NOT NULL,
    kontak VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Aktif',
    joined_at VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial jamaah users
INSERT INTO public.registered_jamaah (nama, kontak, email, password, status, joined_at)
VALUES 
('Yudi Haryono', '0878-1234-1234', 'yudi@gmail.com', '123456', 'Aktif', 'Agt 2026'),
('Rizky Maulana', '0812-9988-7766', 'rizky@gmail.com', '123456', 'Aktif', 'Agt 2026'),
('Budi Santoso', '0813-1122-3344', 'budisan@yahoo.com', '123456', 'Aktif', 'Agt 2026'),
('Annisa Fitri', '0857-4455-6677', 'annisa.f@outlook.com', '123456', 'Aktif', 'Agt 2026'),
('Keluarga Bpk. Herman', '0819-7788-9900', 'herman.fam@gmail.com', '123456', 'Aktif', 'Agt 2026')
ON CONFLICT (kontak) DO NOTHING;

-- --------------------------------------------------------------------
-- 5. TABLE: tanya_dkm (Layanan Aspirasi & Tanya DKM)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tanya_dkm (
    id VARCHAR(100) PRIMARY KEY,
    kategori VARCHAR(100) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    pesan TEXT NOT NULL,
    nama_penanya VARCHAR(255) NOT NULL,
    tanggal VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'Menunggu',
    jawaban_dkm TEXT,
    penjawab_dkm VARCHAR(255),
    tanggal_jawaban VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial tanya DKM items
INSERT INTO public.tanya_dkm (id, kategori, judul, pesan, nama_penanya, tanggal, status, jawaban_dkm, penjawab_dkm, tanggal_jawaban)
VALUES 
('tanya-1', 'Fiqih & Ibadah', 'Bagaimana Ketentuan Zakat Mal untuk Saham & Reksadana?', 'Assalamu''alaikum Ustadz, mohon penjelasan mengenai perhitungan zakat mal untuk instrumen investasi saham syariah dan reksadana.', 'Ahmad Fauzi', '22 Agt 2026', 'Dijawab', 'Wa''alaikumsalam Wr. Wb. Zakat saham & reksadana dihitung dari nilai pasar portofolio ditambah dividen pada saat mencapai haul 1 tahun dan nisab setara 85 gram emas. Besaran zakatnya adalah 2,5%. Anda dapat menggunakan Kalkulator Zakat pada portal ini.', 'Ust. H. Ahmad Farhan, M.A. (Bidang Syariah DKM)', '22 Agt 2026'),
('tanya-2', 'Fasilitas & Kebersihan', 'Saran Tambahan Karpet Shalat & Penyejuk Udara di Mezzanine Wanita', 'Bismillah, mohon dipertimbangkan untuk penambahan kipas angin atau AC di lantai 2 (area shalat wanita) agar jamaah lebih khusyuk saat shalat Jumat.', 'Hamba Allah', '20 Agt 2026', 'Dijawab', 'Jazakallahu khairan atas masukannya. Tim Sarpras DKM telah menyetujui pengadaan 2 unit AC standing di lantai mezzanine pada anggaran bulan ini.', 'Pak Leo (Divisi Sarpras & Pembangunan)', '21 Agt 2026')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------------------
-- 6. TABLE: chart_of_accounts (COA & Neraca Aktivitas ISAK 35)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chart_of_accounts (
    kode VARCHAR(50) PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    kelompok VARCHAR(100) NOT NULL,
    saldo NUMERIC(15, 2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Aktif',
    is_debit BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed COA Data
INSERT INTO public.chart_of_accounts (kode, nama, kategori, kelompok, saldo, status, is_debit)
VALUES 
('1-10001', 'Kas Operasional DKM', 'Aset', 'Aset Lancar', 45000000, 'Aktif', TRUE),
('1-10002', 'Bank BSI Rekening Utama', 'Aset', 'Aset Lancar', 320000000, 'Aktif', TRUE),
('1-10003', 'Bank Muamalat Rekening Wakaf', 'Aset', 'Aset Lancar', 185000000, 'Aktif', TRUE),
('1-10004', 'Kas Kecil Pengurus', 'Aset', 'Aset Lancar', 5000000, 'Aktif', TRUE),
('1-20001', 'Tanah Bangunan Masjid (Wakaf)', 'Aset', 'Aset Tetap', 2500000000, 'Aktif', TRUE),
('1-20002', 'Peralatan Sound System & Sound Digital', 'Aset', 'Aset Tetap', 75000000, 'Aktif', TRUE),
('2-10001', 'Hutang Operasional Listrik & Air', 'Liabilitas', 'Hutang Jangka Pendek', 0, 'Aktif', FALSE),
('3-10001', 'Aset Bersih Tanpa Pembatasan (Infaq Operasional)', 'Aset Bersih', 'Aset Bersih', 370000000, 'Aktif', FALSE),
('3-20001', 'Aset Bersih Dengan Pembatasan (Wakaf & Zakat)', 'Aset Bersih', 'Aset Bersih', 2760000000, 'Aktif', FALSE),
('4-10001', 'Penerimaan Infaq Shalat Jumat', 'Penerimaan', 'Penerimaan Infaq', 15000000, 'Aktif', FALSE),
('4-10002', 'Penerimaan Sedekah Subuh', 'Penerimaan', 'Penerimaan Sedekah', 8500000, 'Aktif', FALSE),
('4-20001', 'Penerimaan Zakat Maal & Fitrah', 'Penerimaan', 'Penerimaan Zakat', 65000000, 'Aktif', FALSE),
('4-30001', 'Penerimaan Wakaf Pembangunan', 'Penerimaan', 'Penerimaan Wakaf', 185000000, 'Aktif', FALSE),
('5-10001', 'Beban Honorarium Marbot & Imam', 'Beban', 'Beban Operasional', 12000000, 'Aktif', TRUE),
('5-10002', 'Beban Kebersihan & Pemeliharaan', 'Beban', 'Beban Operasional', 4500000, 'Aktif', TRUE),
('5-10003', 'Beban Listrik & PDAM', 'Beban', 'Beban Operasional', 3800000, 'Aktif', TRUE)
ON CONFLICT (kode) DO NOTHING;

-- --------------------------------------------------------------------
-- 7. TABLE: jurnal_umum (Jurnal Transaksi Keuangan)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jurnal_umum (
    id VARCHAR(100) PRIMARY KEY,
    tanggal DATE NOT NULL,
    no_bukti VARCHAR(100) NOT NULL,
    keterangan TEXT NOT NULL,
    kode_akun VARCHAR(50) REFERENCES public.chart_of_accounts(kode) ON DELETE CASCADE,
    debit NUMERIC(15, 2) DEFAULT 0,
    kredit NUMERIC(15, 2) DEFAULT 0,
    user_input VARCHAR(255) DEFAULT 'Pengurus DKM',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 8. TABLE: audit_logs (Log Aktivitas Audit Sistem)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    waktu VARCHAR(100) NOT NULL,
    nama VARCHAR(255) NOT NULL,
    peran VARCHAR(100) NOT NULL,
    kontak VARCHAR(100),
    aksi VARCHAR(100) NOT NULL,
    deskripsi TEXT NOT NULL,
    warna_class VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 9. ROW LEVEL SECURITY (RLS) POLICIES FOR PUBLIC & AUTHENTICATED USERS
-- --------------------------------------------------------------------

-- Enable RLS on all tables
ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registered_jamaah ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tanya_dkm ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jurnal_umum ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Allow Public & Anon Read/Write Access Policies
DROP POLICY IF EXISTS "Public Read Programs" ON public.programs;
CREATE POLICY "Public Read Programs" ON public.programs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Programs" ON public.programs;
CREATE POLICY "Public Insert Programs" ON public.programs FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update Programs" ON public.programs;
CREATE POLICY "Public Update Programs" ON public.programs FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Read Donations" ON public.donations;
CREATE POLICY "Public Read Donations" ON public.donations FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Donations" ON public.donations;
CREATE POLICY "Public Insert Donations" ON public.donations FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update Donations" ON public.donations;
CREATE POLICY "Public Update Donations" ON public.donations FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Read Registered Jamaah" ON public.registered_jamaah;
CREATE POLICY "Public Read Registered Jamaah" ON public.registered_jamaah FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Registered Jamaah" ON public.registered_jamaah;
CREATE POLICY "Public Insert Registered Jamaah" ON public.registered_jamaah FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update Registered Jamaah" ON public.registered_jamaah;
CREATE POLICY "Public Update Registered Jamaah" ON public.registered_jamaah FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Read Tanya DKM" ON public.tanya_dkm;
CREATE POLICY "Public Read Tanya DKM" ON public.tanya_dkm FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Tanya DKM" ON public.tanya_dkm;
CREATE POLICY "Public Insert Tanya DKM" ON public.tanya_dkm FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update Tanya DKM" ON public.tanya_dkm;
CREATE POLICY "Public Update Tanya DKM" ON public.tanya_dkm FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Read COA" ON public.chart_of_accounts;
CREATE POLICY "Public Read COA" ON public.chart_of_accounts FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert COA" ON public.chart_of_accounts;
CREATE POLICY "Public Insert COA" ON public.chart_of_accounts FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update COA" ON public.chart_of_accounts;
CREATE POLICY "Public Update COA" ON public.chart_of_accounts FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Read Jurnal" ON public.jurnal_umum;
CREATE POLICY "Public Read Jurnal" ON public.jurnal_umum FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Jurnal" ON public.jurnal_umum;
CREATE POLICY "Public Insert Jurnal" ON public.jurnal_umum FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Audit Logs" ON public.audit_logs;
CREATE POLICY "Public Read Audit Logs" ON public.audit_logs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Audit Logs" ON public.audit_logs;
CREATE POLICY "Public Insert Audit Logs" ON public.audit_logs FOR INSERT WITH CHECK (true);

-- Done! All tables, initial data, and RLS policies configured.

-- --------------------------------------------------------------------
-- 10. TABLE: kegiatan_registrations (Pendaftaran Kegiatan & Kajian)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.kegiatan_registrations (
    id VARCHAR(100) PRIMARY KEY,
    kegiatan_id INT NOT NULL,
    nama VARCHAR(255) NOT NULL,
    kontak VARCHAR(100) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    tanggal_daftar TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 11. TABLE: masjid_inventaris (Manajemen Aset & Inventaris)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.masjid_inventaris (
    id VARCHAR(100) PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    jumlah INT DEFAULT 1,
    kondisi VARCHAR(100) DEFAULT 'Baik',
    tanggal_perolehan DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.kegiatan_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.masjid_inventaris ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Kegiatan" ON public.kegiatan_registrations;
CREATE POLICY "Public Read Kegiatan" ON public.kegiatan_registrations FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Kegiatan" ON public.kegiatan_registrations;
CREATE POLICY "Public Insert Kegiatan" ON public.kegiatan_registrations FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update Kegiatan" ON public.kegiatan_registrations;
CREATE POLICY "Public Update Kegiatan" ON public.kegiatan_registrations FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Public Delete Kegiatan" ON public.kegiatan_registrations;
CREATE POLICY "Public Delete Kegiatan" ON public.kegiatan_registrations FOR DELETE USING (true);

DROP POLICY IF EXISTS "Public Read Inventaris" ON public.masjid_inventaris;
CREATE POLICY "Public Read Inventaris" ON public.masjid_inventaris FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert Inventaris" ON public.masjid_inventaris;
CREATE POLICY "Public Insert Inventaris" ON public.masjid_inventaris FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Delete Inventaris" ON public.masjid_inventaris;
CREATE POLICY "Public Delete Inventaris" ON public.masjid_inventaris FOR DELETE USING (true);

-- --------------------------------------------------------------------
-- 12. VIEWS: Laporan Keuangan Khusus (Untuk Dashboard Supabase)
-- --------------------------------------------------------------------

-- View: kas_masjid (Menampilkan khusus transaksi Pemasukan & Pengeluaran Kas)
CREATE OR REPLACE VIEW public.kas_masjid AS
SELECT 
    ju.id,
    ju.tanggal,
    ju.no_bukti,
    ju.keterangan,
    CASE 
        WHEN ju.debit > 0 THEN 'Pemasukan'
        ELSE 'Pengeluaran'
    END AS jenis_transaksi,
    GREATEST(ju.debit, ju.kredit) AS nominal,
    ju.user_input,
    ju.created_at
FROM 
    public.jurnal_umum ju
WHERE 
    ju.kode_akun LIKE '110%' -- Mengambil hanya akun Kas (1101, 1102, dst)
ORDER BY 
    ju.tanggal DESC;

-- View: buku_besar (Menampilkan rincian Jurnal per Akun)
CREATE OR REPLACE VIEW public.buku_besar AS
SELECT 
    ju.id,
    ju.tanggal,
    ju.no_bukti,
    ju.keterangan,
    ju.kode_akun,
    coa.nama AS nama_akun,
    ju.debit,
    ju.kredit,
    ju.user_input,
    ju.created_at
FROM 
    public.jurnal_umum ju
JOIN 
    public.chart_of_accounts coa ON ju.kode_akun = coa.kode
ORDER BY 
    ju.tanggal DESC;
-- --------------------------------------------------------------------
-- 13. TABLE: admin_users (Data Autentikasi Admin)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nama VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'Aktif',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial admin
INSERT INTO public.admin_users (nama, email, password_hash, role)
VALUES 
('Admin Masjid', 'admin@masjid.com', '123456', 'direktur'),
('Bendahara Masjid', 'bendahara@masjid.com', '123456', 'bendahara')
ON CONFLICT (email) DO NOTHING;

-- --------------------------------------------------------------------
-- 14. TABLE: app_settings (Konfigurasi Aplikasi & Profil)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_settings (
    id INT PRIMARY KEY DEFAULT 1,
    nama_masjid VARCHAR(255) NOT NULL,
    nama_dkm VARCHAR(255) NOT NULL,
    nama_bendahara VARCHAR(255) NOT NULL,
    nama_direktur VARCHAR(255) NOT NULL,
    alamat TEXT,
    kontak_utama VARCHAR(100),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial settings
INSERT INTO public.app_settings (id, nama_masjid, nama_dkm, nama_bendahara, nama_direktur, alamat, kontak_utama)
VALUES (1, 'Masjid Citra Sentul Raya', 'Ustadz H. M. Zainuddin', 'H. Ahmad', 'Prof. Dr. M. Syafii Antonio', 'Jl. Sentul Raya No.1, Bogor', '0812-3456-7890')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------------------
-- 15. TABLE: kajian (Data Daftar Kajian)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.kajian (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    judul VARCHAR(255) NOT NULL,
    ustadz VARCHAR(255) NOT NULL,
    tanggal DATE NOT NULL,
    waktu VARCHAR(100) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    kuota INT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Akan Datang',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 16. TABLE: anggaran (Rencana Anggaran & RAPB)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.anggaran (
    id VARCHAR(100) PRIMARY KEY,
    tahun INT NOT NULL,
    bulan INT NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    nama_kegiatan VARCHAR(255) NOT NULL,
    kode_akun VARCHAR(50) NOT NULL,
    jumlah_dianggarkan NUMERIC(15, 2) NOT NULL,
    jumlah_realisasi NUMERIC(15, 2) DEFAULT 0,
    status VARCHAR(100) DEFAULT 'Draft',
    dibuat_oleh VARCHAR(100),
    riwayat_approval JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- 17. TABLE: pengajuan_pengeluaran (Alur TTD & Approval)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.pengajuan_pengeluaran (
    id VARCHAR(100) PRIMARY KEY,
    tanggal DATE NOT NULL,
    no_pengajuan VARCHAR(100) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    keterangan TEXT,
    kode_akun VARCHAR(50) NOT NULL,
    nama_akun VARCHAR(255) NOT NULL,
    jumlah NUMERIC(15, 2) NOT NULL,
    dibuat_oleh VARCHAR(100) NOT NULL,
    role_permohon VARCHAR(100) NOT NULL,
    status VARCHAR(100) DEFAULT 'Menunggu Bendahara',
    step_aktif INT DEFAULT 1,
    riwayat_approval JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kajian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anggaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengajuan_pengeluaran ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Admin Users" ON public.admin_users;
CREATE POLICY "Public Access Admin Users" ON public.admin_users FOR ALL USING (true);
DROP POLICY IF EXISTS "Public Access App Settings" ON public.app_settings;
CREATE POLICY "Public Access App Settings" ON public.app_settings FOR ALL USING (true);
DROP POLICY IF EXISTS "Public Access Kajian" ON public.kajian;
CREATE POLICY "Public Access Kajian" ON public.kajian FOR ALL USING (true);
DROP POLICY IF EXISTS "Public Access Anggaran" ON public.anggaran;
CREATE POLICY "Public Access Anggaran" ON public.anggaran FOR ALL USING (true);
DROP POLICY IF EXISTS "Public Access Pengajuan" ON public.pengajuan_pengeluaran;
CREATE POLICY "Public Access Pengajuan" ON public.pengajuan_pengeluaran FOR ALL USING (true);

-- --------------------------------------------------------------------
-- 18. VIEWS: Laporan Keuangan Tambahan
-- --------------------------------------------------------------------
CREATE OR REPLACE VIEW public.neraca_view AS
SELECT 
    coa.kode,
    coa.nama AS nama_akun,
    coa.kategori,
    coa.kelompok,
    coa.saldo AS saldo_awal,
    COALESCE(SUM(CASE WHEN coa.is_debit = TRUE THEN ju.debit - ju.kredit ELSE ju.kredit - ju.debit END), 0) + coa.saldo AS saldo_akhir
FROM 
    public.chart_of_accounts coa
LEFT JOIN 
    public.jurnal_umum ju ON coa.kode = ju.kode_akun
WHERE 
    coa.kategori IN ('Aset', 'Liabilitas', 'Ekuitas', 'Aset Bersih')
GROUP BY 
    coa.kode, coa.nama, coa.kategori, coa.kelompok, coa.saldo, coa.is_debit;

CREATE OR REPLACE VIEW public.laba_rugi_view AS
SELECT 
    coa.kode,
    coa.nama AS nama_akun,
    coa.kategori,
    coa.kelompok,
    COALESCE(SUM(CASE WHEN coa.is_debit = FALSE THEN ju.kredit - ju.debit ELSE ju.debit - ju.kredit END), 0) AS total_mutasi
FROM 
    public.chart_of_accounts coa
LEFT JOIN 
    public.jurnal_umum ju ON coa.kode = ju.kode_akun
WHERE 
    coa.kategori IN ('Penerimaan', 'Pendapatan', 'Beban')
GROUP BY 
    coa.kode, coa.nama, coa.kategori, coa.kelompok, coa.is_debit;

